# Path configuration
import os

"""
System configuration file
Contains global constants and configurations
"""

# Window configuration
WINDOW_TITLE = "Full Stack Compiler - Adriel S. Chaves Salazar"
FPS = 60

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
GRAY = (128, 128, 128)

# Application states
class States:
    EDITOR = "EDITOR"  # Main editor state
    LEXICAL_ANALYSIS = "LEXICAL_ANALYSIS"  #1st compilation state
    SYNTACTIC_ANALYSIS = "SYNTACTIC_ANALYSIS" #2nd compilation state
    SEMANTIC_ANALYSIS = "SEMANTIC_ANALYSIS" #3rd compilation state
    IR_CODE_VIEW = "IR_CODE_VIEW" #4th compilation state
    IR_OPTIMIZED = "IR_OPTIMIZED" #5th compilation state
    MACHINE_CODE = "MACHINE_CODE" #6th compilation state
    

# Font size configurations
# Tamaños para la opción "small"
FONT_SIZE_SMALL_OPTION = {
    "small": 10,
    "medium": 12,
    "large": 15
}

# Tamaños para la opción "medium"
FONT_SIZE_MEDIUM_OPTION = {
    "small": 12,
    "medium": 18,
    "large": 22
}

# Tamaños para la opción "large"
FONT_SIZE_LARGE_OPTION = {
    "small": 14,
    "medium": 22,
    "large": 26
}

# Default font sizes (small option)
DEFAULT_FONT_SIZE_SMALL = FONT_SIZE_SMALL_OPTION["small"]
DEFAULT_FONT_SIZE_MEDIUM = FONT_SIZE_SMALL_OPTION["medium"]
DEFAULT_FONT_SIZE_LARGE = FONT_SIZE_SMALL_OPTION["large"]

# TextBox configuration
LINE_NUMBERS_WIDTH = 80  # width of line numbers area
LINE_HEIGHT_MULTIPLIER = 2  # multiplier for line height (doubles the height)
KEY_REPEAT_DELAY = 450  # ms before key starts repeating
KEY_REPEAT_INTERVAL = 25  # ms between repeats (over 60 times/second)
LINE_SEPARATOR_THICKNESS = 1  # thickness of line separators in pixels

# Project directory
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Assets directory (if needed)
ASSETS_DIR = os.path.join(BASE_DIR, "assets")
FONTS_DIR = os.path.join(ASSETS_DIR, "fonts")
MAIN_FONT = "ttf/JetBrainsMono-Regular.ttf"  # Nombre del archivo de fuente

# Path to the image binary generated by the compiler
IMAGE_BIN_PATH = os.path.join(BASE_DIR, "out", "image.bin")

# Grammar path
GRAMMAR_PATH = os.path.join(BASE_DIR, "assets", "VGraph.g4")

# Grammar content
try:
    with open(GRAMMAR_PATH, 'r') as file:
        GRAMMAR = file.read()
except Exception as e:
    print(f"Error al leer el archivo de gramática: {e}")
    GRAMMAR = ""  # Valor por defecto en caso de error

# Camera view settings for symbol table visualization
SYMBOL_TABLE_CAMERA_WIDTH = 350
SYMBOL_TABLE_CAMERA_HEIGHT = 350

# Rutas para archivos del análisis semántico
SEMANTIC_GRAPH_PATH = os.path.join(ASSETS_DIR, "Images", "semantic_graph.png")
ENHANCED_SYMBOL_TABLE_PATH = os.path.join(ASSETS_DIR, "Images", "enhanced_symbol_table.png")

# Datos compartidos entre analizadores
class CompilerData:
    """Clase estática para almacenar datos compartidos entre las fases del compilador"""
    # Rutas a archivos de visualización
    token_graph_path = None
    parse_tree_path = None
    symbol_table_path = None
    semantic_graph_path = None
    enhanced_symbol_table_path = None
    semantic_tree_path = None
    ir_raw = None
    ir_optimized = None
    
    # Datos del análisis léxico
    tokens = []
    lexical_errors = []
    
    # Datos del análisis sintáctico
    syntactic_errors = []
    ast = None  # Abstract Syntax Tree
    parser = None  # Parser reference (needed for tree traversal)
    symbol_table = {}  # Tabla de símbolos inicial
    
    # Datos del análisis semántico
    semantic_errors = []
    enhanced_symbol_table = {}  # Tabla de símbolos con información de tipos
    semantic_tree = {}
    
    @staticmethod
    def reset_lexical():
        """Resetea los datos del análisis léxico"""
        CompilerData.tokens = []
        CompilerData.lexical_errors = []
        CompilerData.token_graph_path = None
    
    @staticmethod
    def reset_syntactic():
        """Resetea los datos del análisis sintáctico"""
        CompilerData.ast = None
        CompilerData.parser = None
        CompilerData.symbol_table = {}
        CompilerData.syntactic_errors = []
        CompilerData.parse_tree_path = None
        CompilerData.symbol_table_path = None
    
    @staticmethod
    def reset_semantic():
        """Resetea los datos del análisis semántico"""
        CompilerData.semantic_errors = []
        CompilerData.enhanced_symbol_table = {}
        CompilerData.semantic_graph_path = None
        CompilerData.enhanced_symbol_table_path = None
        CompilerData.semantic_tree_path = None
        CompilerData.semantic_tree = None
    
    @staticmethod
    def reset_all():
        """Resetea todos los datos del compilador"""
        CompilerData.reset_lexical()
        CompilerData.reset_syntactic()
        CompilerData.reset_semantic()

    @staticmethod
    def get_ast_visualization():
        """Genera una visualización del AST almacenado"""
        if not CompilerData.ast or not CompilerData.parser:
            return "No hay árbol de análisis sintáctico disponible"
        
        # Importar dinámicamente para evitar dependencias circulares
        from CompilerLogic.SemanticComponents.astUtil import print_ast
        return print_ast(CompilerData.ast, CompilerData.parser)