# Path configuration
import os

"""
System configuration file
Contains global constants and configurations
"""

# Window configuration
WINDOW_TITLE = "Full Stack Compiler - Adriel S. Chaves Salazar"
FPS = 60

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
GRAY = (128, 128, 128)

# Application states
class States:
    EDITOR = "EDITOR"  # Main editor state
    LEXICAL_ANALYSIS = "LEXICAL_ANALYSIS"  #1st compilation state
    SYNTACTIC_ANALYSIS = "SYNTACTIC_ANALYSIS" #2nd compilation state

# Font size configurations
# Tamaños para la opción "small"
FONT_SIZE_SMALL_OPTION = {
    "small": 10,
    "medium": 12,
    "large": 15
}

# Tamaños para la opción "medium"
FONT_SIZE_MEDIUM_OPTION = {
    "small": 12,
    "medium": 18,
    "large": 22
}

# Tamaños para la opción "large"
FONT_SIZE_LARGE_OPTION = {
    "small": 14,
    "medium": 22,
    "large": 26
}

# Default font sizes (small option)
DEFAULT_FONT_SIZE_SMALL = FONT_SIZE_SMALL_OPTION["small"]
DEFAULT_FONT_SIZE_MEDIUM = FONT_SIZE_SMALL_OPTION["medium"]
DEFAULT_FONT_SIZE_LARGE = FONT_SIZE_SMALL_OPTION["large"]

# TextBox configuration
LINE_NUMBERS_WIDTH = 80  # width of line numbers area
LINE_HEIGHT_MULTIPLIER = 2  # multiplier for line height (doubles the height)
KEY_REPEAT_DELAY = 450  # ms before key starts repeating
KEY_REPEAT_INTERVAL = 25  # ms between repeats (over 60 times/second)
LINE_SEPARATOR_THICKNESS = 1  # thickness of line separators in pixels

# Project directory
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Assets directory (if needed)
ASSETS_DIR = os.path.join(BASE_DIR, "assets")
FONTS_DIR = os.path.join(ASSETS_DIR, "fonts")
MAIN_FONT = "ttf/JetBrainsMono-Regular.ttf"  # Nombre del archivo de fuente

# Path to the image binary generated by the compiler
IMAGE_BIN_PATH = os.path.join(BASE_DIR, "out", "image.bin")

# Grammar path
GRAMMAR_PATH = os.path.join(BASE_DIR, "assets", "VGraph.g4")

# Grammar content
try:
    with open(GRAMMAR_PATH, 'r') as file:
        GRAMMAR = file.read()
except Exception as e:
    print(f"Error al leer el archivo de gramática: {e}")
    GRAMMAR = ""  # Valor por defecto en caso de error

# Camera view settings for symbol table visualization
SYMBOL_TABLE_CAMERA_WIDTH = 350
SYMBOL_TABLE_CAMERA_HEIGHT = 350